
from PyQt5 import QtCore, QtGui, QtWidgets

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig)

class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName(_fromUtf8("main_window"))
        main_window.resize(747, 532)
        self.centralWidget = QtWidgets.QWidget(main_window)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.line = QtWidgets.QFrame(self.centralWidget)
        self.line.setGeometry(QtCore.QRect(430, 0, 20, 471))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.Slide_Horizontal = QtWidgets.QSlider(self.centralWidget)
        self.Slide_Horizontal.setGeometry(QtCore.QRect(140, 356, 160, 20))
        self.Slide_Horizontal.setMinimum(-1280)
        self.Slide_Horizontal.setMaximum(1280)
        self.Slide_Horizontal.setOrientation(QtCore.Qt.Horizontal)
        self.Slide_Horizontal.setObjectName(_fromUtf8("Slide_Horizontal"))
        self.Slide_Vertical = QtWidgets.QSlider(self.centralWidget)
        self.Slide_Vertical.setGeometry(QtCore.QRect(140, 388, 160, 21))
        self.Slide_Vertical.setMinimum(-768)
        self.Slide_Vertical.setMaximum(768)
        self.Slide_Vertical.setOrientation(QtCore.Qt.Horizontal)
        self.Slide_Vertical.setObjectName(_fromUtf8("Slide_Vertical"))
        self.Slide_Gray = QtWidgets.QSlider(self.centralWidget)
        self.Slide_Gray.setGeometry(QtCore.QRect(140, 420, 160, 21))
        self.Slide_Gray.setMaximum(255)
        self.Slide_Gray.setProperty("value", 255)
        self.Slide_Gray.setOrientation(QtCore.Qt.Horizontal)
        self.Slide_Gray.setObjectName(_fromUtf8("Slide_Gray"))
        self.SB_horizontal = QtWidgets.QSpinBox(self.centralWidget)
        self.SB_horizontal.setGeometry(QtCore.QRect(320, 352, 61, 27))
        self.SB_horizontal.setMinimum(-1280)
        self.SB_horizontal.setMaximum(1280)
        self.SB_horizontal.setObjectName(_fromUtf8("SB_horizontal"))
        self.SB_vertical = QtWidgets.QSpinBox(self.centralWidget)
        self.SB_vertical.setGeometry(QtCore.QRect(320, 386, 61, 27))
        self.SB_vertical.setMinimum(-768)
        self.SB_vertical.setMaximum(768)
        self.SB_vertical.setObjectName(_fromUtf8("SB_vertical"))
        self.SB_gray = QtWidgets.QSpinBox(self.centralWidget)
        self.SB_gray.setGeometry(QtCore.QRect(320, 418, 61, 27))
        self.SB_gray.setMaximum(255)
        self.SB_gray.setProperty("value", 255)
        self.SB_gray.setObjectName(_fromUtf8("SB_gray"))
        self.PB_addImage = QtWidgets.QPushButton(self.centralWidget)
        self.PB_addImage.setGeometry(QtCore.QRect(10, 40, 101, 29))
        self.PB_addImage.setObjectName(_fromUtf8("PB_addImage"))
        self.PB_removeImage = QtWidgets.QPushButton(self.centralWidget)
        self.PB_removeImage.setGeometry(QtCore.QRect(130, 40, 101, 29))
        self.PB_removeImage.setObjectName(_fromUtf8("PB_removeImage"))
        self.PB_showImage = QtWidgets.QPushButton(self.centralWidget)
        self.PB_showImage.setGeometry(QtCore.QRect(10, 280, 101, 29))
        self.PB_showImage.setObjectName(_fromUtf8("PB_showImage"))
        self.PB_StartHost = QtWidgets.QPushButton(self.centralWidget)
        self.PB_StartHost.setGeometry(QtCore.QRect(460, 40, 101, 29))
        self.PB_StartHost.setObjectName(_fromUtf8("PB_StartHost"))
        self.PB_hostPause = QtWidgets.QPushButton(self.centralWidget)
        self.PB_hostPause.setGeometry(QtCore.QRect(460, 80, 101, 29))
        self.PB_hostPause.setObjectName(_fromUtf8("PB_hostPause"))
        self.CB_hostSwap = QtWidgets.QCheckBox(self.centralWidget)
        self.CB_hostSwap.setGeometry(QtCore.QRect(580, 60, 151, 22))
        self.CB_hostSwap.setObjectName(_fromUtf8("CB_hostSwap"))
        self.PB_stopHost = QtWidgets.QPushButton(self.centralWidget)
        self.PB_stopHost.setGeometry(QtCore.QRect(460, 360, 101, 29))
        self.PB_stopHost.setObjectName(_fromUtf8("PB_stopHost"))
        self.line_2 = QtWidgets.QFrame(self.centralWidget)
        self.line_2.setGeometry(QtCore.QRect(0, 320, 441, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(56, 357, 81, 17))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(57, 389, 67, 17))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtWidgets.QLabel(self.centralWidget)
        self.label_3.setGeometry(QtCore.QRect(58, 419, 67, 17))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtWidgets.QLabel(self.centralWidget)
        self.label_4.setGeometry(QtCore.QRect(10, 330, 131, 17))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtWidgets.QLabel(self.centralWidget)
        self.label_5.setGeometry(QtCore.QRect(20, 10, 91, 17))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtWidgets.QLabel(self.centralWidget)
        self.label_6.setGeometry(QtCore.QRect(460, 10, 67, 17))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.TB_host = QtWidgets.QPlainTextEdit(self.centralWidget)
        self.TB_host.setGeometry(QtCore.QRect(460, 120, 251, 231))
        self.TB_host.setReadOnly(True)
        self.TB_host.setObjectName(_fromUtf8("TB_host"))
        self.LW_paths = QtWidgets.QListWidget(self.centralWidget)
        self.LW_paths.setGeometry(QtCore.QRect(10, 80, 421, 192))
        self.LW_paths.setObjectName(_fromUtf8("LW_paths"))
        self.PB_imageClose = QtWidgets.QPushButton(self.centralWidget)
        self.PB_imageClose.setGeometry(QtCore.QRect(130, 280, 101, 29))
        self.PB_imageClose.setObjectName(_fromUtf8("PB_imageClose"))
        self.CB_graySwap = QtWidgets.QCheckBox(self.centralWidget)
        self.CB_graySwap.setGeometry(QtCore.QRect(290, 450, 101, 22))
        self.CB_graySwap.setObjectName(_fromUtf8("CB_graySwap"))
        main_window.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(main_window)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 747, 19))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        main_window.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(main_window)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        main_window.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(main_window)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        main_window.setStatusBar(self.statusBar)

        self.retranslateUi(main_window)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        main_window.setWindowTitle(_translate("main_window", "main_window", None))
        self.PB_addImage.setText(_translate("main_window", "Add", None))
        self.PB_removeImage.setText(_translate("main_window", "Remove", None))
        self.PB_showImage.setText(_translate("main_window", "Show", None))
        self.PB_StartHost.setText(_translate("main_window", "Start Host", None))
        self.PB_hostPause.setText(_translate("main_window", "Pause Host", None))
        self.CB_hostSwap.setText(_translate("main_window", "Swap on message", None))
        self.PB_stopHost.setText(_translate("main_window", "Stop Host", None))
        self.label.setText(_translate("main_window", "Horizontal", None))
        self.label_2.setText(_translate("main_window", "Vertical", None))
        self.label_3.setText(_translate("main_window", "Gray", None))
        self.label_4.setText(_translate("main_window", "Image Manipulation", None))
        self.label_5.setText(_translate("main_window", "Image Select", None))
        self.label_6.setText(_translate("main_window", "Host", None))
        self.PB_imageClose.setText(_translate("main_window", "Close", None))
        self.CB_graySwap.setText(_translate("main_window", "Swap Gray", None))

